const CHARACTERS_LETTERS =
  "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
const CHARACTERS_NUMBERS = "0123456789";
const CHARACTERS_SPECIAL = "!@#$%^&*()_+~`|}{[]:;?><,./-=";
const CHARACTERS_LETTERS_NUMBERS = CHARACTERS_LETTERS + CHARACTERS_NUMBERS;
const CHARACTERS_LETTERS_NUMBERS_SPECIAL =
  CHARACTERS_LETTERS_NUMBERS + CHARACTERS_SPECIAL;

const LENGTH_MIN = 1;
const LENGTH_MAX = 10000;

const LENGTH_MIN_EMAIL = 3;
const LENGTH_MAX_EMAIL = 10000;

const LENGTH_MIN_PASSWORD = 8;
const LENGTH_MAX_PASSWORD = 10000;

const METHODS = {
  POST: "POST",
  GET: "GET",
  PUT: "PUT",
  PATCH: "PATCH",
  DELETE: "DELETE",
};
const HTTP_STATUS_CODE = {
  OK: 200,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  UNPROCESSABLE_ENTITY: 422,
};

const CONTENT_TYPE = {
  JSON: "application/json",
  URL_ENCODED: "application/x-www-form-urlencoded",
  TEXT_PLAIN: "text/plain",
  XML: "application/xml",

}
export {
  CHARACTERS_LETTERS,
  CHARACTERS_NUMBERS,
  CHARACTERS_SPECIAL,
  CHARACTERS_LETTERS_NUMBERS,
  CHARACTERS_LETTERS_NUMBERS_SPECIAL,
  LENGTH_MIN,
  LENGTH_MAX,
  LENGTH_MIN_EMAIL,
  LENGTH_MAX_EMAIL,
  LENGTH_MIN_PASSWORD,
  LENGTH_MAX_PASSWORD,
  METHODS,
  HTTP_STATUS_CODE,
  CONTENT_TYPE,
};
